### ISSUE TITLE
Requirements Document - Grammar, Spelling, and Clarity

### ISSUE THREAD

**Issue by rahelC** [LucianoAbbott/UPOD#15]
- **Purpose**
  - The purpose should let the readers know why they need to read this document. Currently, it just states what the document is.
- **Scope**
  - "..to allow for _easy access_ and _updating_.." : Should be more specific on "access and updating".
- **Definitions**
  - The definitions are key terms as they are used in this document. So don't need to put what the HTML, and CSS are.
  - Should add more acronyms. "web application" used in Introduction, and "Host" used in Functional Requirements.
  - "..made up of HTML and CSS." : Unnecessary to mention which languages we are going to use. Just say "..made up of programming languages."
  - "_Hypertext_ Markup Language" instead of "HyperText Markup Language"
  - "The _protion_ of.." : misspelled word
- **Overview**
  - The last sentence is unclear, and questionable.
- **Overall Description**
  - Use "self-contained" instead of "self contained".
  - Use "website" instead of "web site".
  - "..information that physics _covers,_ the site will have to be.." : Add comma.
  - Change "be easily navigable and intuitive as well as informative." to "be intuitive, informative, and easy to navigate."
  - "To ensure the site is _informative,_ a variety of tools.." : Add comma.
- **Product Perspective**
  - The first sentence is confusing. Should have said like "The UPOD site uses user based data, and will be integrated into.."
  - "..for the following _browsers._" : Add dot at the end.
  - Change "UPOD's user interface" to "UPOD's user interface (UI)".
  - I think the last sentence should be "UPOD's user interface (UI) will support the desktop version only."
- **Product Functions**
  - Change "Admin functions" to "Administrator Functions".
  - "..be able to _promote,_ and.." : Add comma.
  - Change "..revoke moderator status to a user." to "..revoke moderator status to and from user status."
- **User Characteristics**
  - In Moderators part,
      - Could use "higher" instead of "greater".
      - Change "..however, if _they_ wish to.." to "..however, if moderators wish to.."
      - Change "..diagram, _the moderator_ must know.." to "..diagram, they must know.."
      - Change "javascript" to "JavaScript".
      - If the moderators need to know JavaScript, then they would also need to know what the HTML, and CSS is.
  - In Administrators part,
      - "..to the _existing list_." : Could say like "pre-existing ones" instead of "the existing list".
      - Change "..degree of _knowledge_.." to "..degree of physics knowledge.."
- **Constraints**
  - "..a lack of _resources,_ we.." : Add comma.
- **Assumptions and Dependencies**
  - Change "..that _any user_ will.." to "..that general users will.."
  - The last sentence is a fragment, needs completion.
- **Functional Requirements**
  - Should consider the moderator's login as well.
  - In Administrative Login,
      - Change "_app_" to "application".
      - "Host signs in to an _existing_." : "existing" is unclear.
      - "Multiple administrators can login." : Does it mean that several users can login as administrator at the same time?
  - In Search UPOD,
      - "No results are found presents user with an empty results page stating that no results were found." : The sentence is confusing.
      - Add the case that the user submits a query without any input on the search bar.
- **Security**
  - "..the Laurier _Databases,_ so the.." : Add comma.
  - "Professors" : Should not be capitalized.
  - "..edit the _website,_ as well as.." : Add comma.

**Comment by Advanderar** [comment]
> I think the last sentence should be 'UPOD's user interface (UI) will support the desktop version only.'

- No matter how the site is programed it will be technically viewable on mobile which means there will be mobile support just not mobile formatting so I think the original wording is appropriate.

>  "Could use 'higher' instead of 'greater'".

- Higher knowledge is usually associated with religious and spiritual knowledge not technical understanding. I think the original wording is appropriate. 

> "If the moderators need to know JavaScript, then they would also need to know what the HTML, and CSS is."

- No, The front end team will develop an application that develops a page using moderator input using a simple text box formatting interface. Therefore the only people who need coding experience are people making JS applets.
