### ISSUE TITLE
Project Management Document - Grammar, Spelling, Consistency

### ISSUE THREAD

**Issue by ziyii** [LucianoAbbott/UPOD#19]
- All the titles should be capitalized (i.e. _"Project summary"_ should be _"Project Summary"_). Throughout the document, some are and some aren't. 
- In the table of contents, titles are missing the Oxford comma: 
1.1.1 _"Purpose, scope and objectives"_ to _"Purpose, Scope, and Objectives"_
6.2 _"Methods, tools and techniques"_ to _"Methods, Tools, and Techniques"_

**The Sections**
1.1.1 Missing Oxford comma. Also use _"as well as"_ instead of the 2nd _"and."_ _"[...] for students to access physics, information, equations and diagrams and for professors to add, edit and remove those components."_ to _"[...] for students to access physics, information, equations, and diagrams as well as for professors to add, edit, and remove those components."_

1.1.3 Missing Oxford comma. _"[...] documentation, work logs, source code and all other documents [...]"_

3 Capitalize the SQA definition to _"Software Quality Assurance"_. 

4.1 I noticed that the Requirements doc is using the dash and the second half of the Project Management doc is using the dash, so for consistency, change _"front end"_ and _"back end"_ to _"front-end"_ and _"back-end"_. 

4.2 Capitalize titles. (i.e. _"Client contact"_ to _"Client Contact"_)

5.1.3 Spelling. _"Aquisition"_ to _"Acquisition"_. _"aquired"_ to _"acquired"_. _"nnor"_ to _"nor"_. 

5.2.2 _"Scheduling is the be determined"_. Change the _"the"_ to _"to"_. 
_"The basics of the Schedule will kept in [...]"_ missing _"be"_ after _"will"_. 

5.3.1 _"Channges"_ has one too many Ns. 
_"combinantion"_ spelling.
_"annd"_ has one too many Ns. 
_"recieve"_ spelling. 
_"onnly"_ someone has an N problem. 
_"memebers"_ spelling. 
Should be _"Changes, combination, and, receive, only, members"_ respectively. 

5.3.2 The first sentence is a run on sentence. Also check spelling. There's _"annd, andn, determinen, annd, intno, seperate"_ when they should be _"and, and, determine, and, into, separate"_ respectively. 

5.3.4 _"These testers are demonstrate, [...]"_ missing _"to"_. 
Spelling _"qualitiy, mannnenr, thouroughly"_ to _"quality, manner, thoroughly"_ respectively. 

6.1 Either add a period to the end of each phase description or get rid of the one from phase 1. 

6.2 _"Methods, Tools, And Techniques"_ un-capitalize the _"and"_

**Comment by boud7430** [comment]
I think I've fixed all of these.

**Comment by ziyii** [comment]
Yes, thank you! 

You definitely got 'em good. There's just three more things from me:

In the **Table of Contents**, 5.1 _"Startup plans"_ needs a capital _"P"_ 

**5.1.3** There's one more _"aquired"_ that needs to be changed to _"acquired"_

**5.3.5** In here there's a _"gitHub"_ while in Sections 6.3, 7.2, 7.3, it's _"GitHub"_

**Comment by abelworku** [comment]
Hi Ziyi this is Abel, I've fixed the issues you've pointed out, thanks for spotting them.
