### ISSUE TITLE
Project Management Planning Document SQA

### ISSUE THREAD

**Issue by LucianoAbbott** [LucianoAbbott/UPOD#21]
**1.1 Project Summary**
- Improper capitalization for _"Project summary"_, and _"Purpose, scope, and Objectives"_

**4.1 Structure**

- Luciano Abbott, Stephanie Pitman, and Ziyi Zhang are listed in both Front-End and Back-End, consider removing them from one group for simplicity

**5.1.1 Estimation Plan**
- _"However, the methods and work required to meet a given deadline are estimated using prior experience as a reference for time take"_ last few words of the sentence need revision.

**5.2 Work Plan**
-  Improper capitalization for _"Work activities"_, and _"Schedule allocation"_

**5.2.2 Schedule Allocation**
- _"determinned"_ typo.

**6.1 Process Model**
-_"Initialization of group tasks"_ initialization is not the right word. (Initiation? Creation?)

**6.4 Product Acceptance Plan**
-_"SQA [Software Quality Assurance]"_ clarification after SQA is unnecessary because the acronym is defined above.
-Shorten Software Quality Assurance to SQA

**7 Supporting Process Plans**
-Improper capitalization for _"Supporting process plans"_

**Comment by abelworku** [comment]
Hi Luciano I think I've fixed the issues here, let me know if I've missed anything :D.
